name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.PRIVATE_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      
      - name: Build Docker image
        run: docker build -t front:latest .

      - name: Save Docker image as tar file
        run: |
          docker save -o front.tar front:latest
          chmod 664 front.tar

      - name: Transfer files to remote server
        uses: appleboy/scp-action@master
        with:
          host: 195.210.3.88
          username: prog
          port: 2121
          key: ${{ secrets.PRIVATE_KEY }}
          source: "front.tar,deploy/*"
          target: ./front

      - name: Load Docker image on remote server
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no prog@195.210.3.88 -p 2121 << 'ENDSSH'
          docker load -i ~/front/front.tar
          ENDSSH
      
      - name: Deploy Docker containers using Docker Compose on remote server
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no prog@195.210.3.88 -p 2121 << 'ENDSSH'
          docker compose -f ~/front/deploy/docker-compose.yaml up -d
          ENDSSH
              

