name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      
      - name: Build Docker image
        run: docker build -t front:latest .

      - name: Save Docker image as tar file
        run: |
          docker save -o front.tar front:latest
          chmod 664 front.tar

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@master
        with:
          host: 5.35.84.206
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: front.tar
          target: ./images

      - name: Load Docker image on remote server
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no root@5.35.84.206 << 'ENDSSH'
          docker load -i ~/images/front.tar
          ENDSSH

      - name: Transfer Docker Compose file to remote server
        uses: appleboy/scp-action@master
        with:
          host: 5.35.84.206
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: docker-compose.yaml
          target: ./dc
      
      - name: Deploy Docker containers using Docker Compose on remote server
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no root@5.35.84.206 << 'ENDSSH'
          docker compose -f ~/dc/docker-compose.yaml up -d
          ENDSSH
              

