name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      #- run: yarn install
      # - run: npm run build
      # - run: yarn build
      # Deploy
      #- run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete ./ root@lbifadjrwd:../var/www/html/.output
      # - run: "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no root@5.35.84.206 reboot"
      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Save Docker image as tar file
        run: |
          docker save -o my-image.tar my-image:latest-dev
          chmod 664 my-image.tar

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 5.35.84.206
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: my-image.tar
          target: ./images

        #run: scp -o "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" my-image.tar root@5.35.84.206:images

      - name: Load Docker image on remote server
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no root@5.35.84.206 << 'ENDSSH'
          docker load -i ~/images/my-image.tar
          ENDSSH

      - name: Transfer Docker Compose file to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 5.35.84.206
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: docker-compose.yaml
          target: ./dc
        # run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete ./docker-compose.yaml root@5.35.84.206:../dc

      - name: Deploy Docker containers using Docker Compose on remote server
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no root@5.35.84.206 << 'ENDSSH'
          docker compose -f ~/dc/docker-compose.yaml up -d
          ENDSSH  

